### ISSUE TITLE
React Components not mounting?

### ISSUE THREAD

**Issue by samblackk** [liron-navon/slate-react-starter#1]
Loaded straight from the install, no modifications, and the example `theme-react-wrapper` element doesn't compile into `ExampleComponent`. Is the intended function for the selector element to be replaced with the React component?

**Comment by jrgreiner115** [comment]
@singram26, can you explain your solution? I'm caught right behind you, just when I start including multiple components.

**Comment by mateowinn** [comment]
@jrgreiner115 I ran into the same issues. [This thread](https://github.com/Shopify/slate/issues/726#issuecomment-425675011) helped me a lot. I had to re-do the Slate SSL cert instructions, but one key element is still missing: the extra `mkcert -install` command. Try it out and see if that helps!
